### ISSUE TITLE
Bug: Player cannot fit through 1 block wide spaces

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/cube_puzzler#1] opened 2022-11-06 02:01 UTC
Level recreation sample: `95a5b20a5b20a45bc34b/225a/225a/225a/225a/160a15b35a5b5a5b`

**Comment by Jackal-42** [comment] 2022-11-06 02:29
Just confirming, this is how the example level should look? It seemed a bit odd to me. I want to make sure the code loader works as intended.<br><img width="336" alt="image" src="https://user-images.githubusercontent.com/91426054/200151136-206f3ed6-f598-4694-8d05-d36d1402b07e.png">

**Comment by Jackal-42** [comment] 2022-11-08 19:24
v0.1 reduces the size of the player's hitbox by a small margin, resolving this issue.

**Closed as completed by Jackal-42** 2022-11-08 19:24 UTC

**Comment by robtech21** [comment] 2022-11-09 14:26
I meant to create a pathway on the starting area
